
export const getMockApartments = () => [
  {
    id: '1',
    name: 'סוויטת חוף חלומית פרימיום',
    imageUrl: 'https://picsum.photos/seed/apt1/600/400',
    city: 'תל אביב',
    street: 'הירקון 100, קומה 5',
    rooms: 3,
    pricePerNight: 850,
    rating: 4.8,
    amenities: ['WiFi מהיר', 'נוף פנורמי לים', 'מטבח שף', 'חניה פרטית', 'שירות חדרים'],
    description: 'סוויטה מרווחת ומעוצבת עם מרפסת גדולה המשקיפה ישירות לחוף הים. אידיאלית למשפחות וזוגות המחפשים חופשה יוקרתית.',
    isPremium: true,
  },
  {
    id: '2',
    name: 'דירת גן קסומה בירושלים',
    imageUrl: 'https://picsum.photos/seed/apt2/600/400',
    city: 'ירושלים',
    street: 'עמק רפאים 25',
    rooms: 2,
    pricePerNight: 600,
    rating: 4.5,
    amenities: ['גינה פרטית', 'כניסה נפרדת', 'שקט ופסטורלי', 'קרוב למרכז'],
    description: 'דירת גן מקסימה ושקטה בלב המושבה הגרמנית. כוללת גינה ירוקה ומטופחת, מושלמת לארוחות בוקר באוויר הפתוח.',
    isPremium: false,
  },
  {
    id: '3',
    name: 'פנטהאוז יוקרתי באילת',
    imageUrl: 'https://picsum.photos/seed/apt3/600/400',
    city: 'אילת',
    street: 'משעול הדולפין 7',
    rooms: 4,
    pricePerNight: 1200,
    rating: 4.9,
    amenities: ['בריכה פרטית על הגג', 'ג\'קוזי', 'חדר קולנוע', 'שירותי קונסיירז\''],
    description: 'פנטהאוז עוצר נשימה עם נוף למפרץ אילת. מציע חווית אירוח אקסקלוסיבית עם כל הפינוקים האפשריים.',
    isPremium: true,
  },
  {
    id: '4',
    name: 'בקתת עץ בגליל',
    imageUrl: 'https://picsum.photos/seed/apt4/600/400',
    city: 'ראש פינה',
    street: 'דרך היין 12',
    rooms: 1,
    pricePerNight: 550,
    rating: 4.6,
    amenities: ['אווירה כפרית', 'קמין', 'מרפסת נוף', 'טיפולי ספא (בהזמנה)'],
    description: 'בקתת עץ רומנטית ומבודדת בלב הטבע הגלילי. המקום המושלם לברוח מהמולת היום-יום ולהתחבר לשקט ולשלווה.',
    isPremium: false,
  },
  {
    id: '5',
    name: 'דירה אורבנית בחיפה',
    imageUrl: 'https://picsum.photos/seed/apt5/600/400',
    city: 'חיפה',
    street: 'שדרות הנשיא 88',
    rooms: 2,
    pricePerNight: 480,
    rating: 4.3,
    amenities: ['מרפסת שמש', 'קרוב לכרמלית', 'מעוצבת מודרנית', 'פינת עבודה'],
    description: 'דירה שיקית ומוארת במרכז הכרמל, קרובה לבתי קפה, מסעדות ומוקדי תרבות. נוחה ונגישה לתחבורה ציבורית.',
    isPremium: false,
  },
  {
    id: '6',
    name: 'וילה עם בריכה בקיסריה - VIP',
    imageUrl: 'https://picsum.photos/seed/apt6/600/400',
    city: 'קיסריה',
    street: 'הנבל 5',
    rooms: 5,
    pricePerNight: 2500,
    rating: 5.0,
    amenities: ['בריכה גדולה ומחוממת', 'חצר מטופחת', 'שולחן ביליארד', 'מטבח חיצוני מאובזר', 'סאונה יבשה'],
    description: 'וילה מפוארת ומרווחת במיקום יוקרתי בקיסריה. מתאימה למשפחות גדולות או קבוצות חברים המחפשים חופשה בלתי נשכחת ברמה הגבוהה ביותר.',
    isPremium: true,
  },
  {
    id: '7',
    name: 'לופט מעצבים בתל אביב',
    imageUrl: 'https://picsum.photos/seed/apt7/600/400',
    city: 'תל אביב',
    street: 'רוטשילד 10',
    rooms: 2,
    pricePerNight: 950,
    rating: 4.7,
    amenities: ['עיצוב אדריכלי', 'תקרות גבוהות', 'מערכת סאונד', 'מרפסת אורבנית'],
    description: 'לופט מרהיב בלב תל אביב, מעוצב בקפידה עם חלל פתוח ומואר. חוויה אורבנית מושלמת.',
    isPremium: false,
  },
  {
    id: '8',
    name: 'סוויטת אבן עתיקה בצפת',
    imageUrl: 'https://picsum.photos/seed/apt8/600/400',
    city: 'צפת',
    street: 'סמטת האמנים 3',
    rooms: 1,
    pricePerNight: 700,
    rating: 4.9,
    amenities: ['קירות אבן חשופים', 'אווירה רוחנית', 'ג\'קוזי פנימי', 'נוף להרים'],
    description: 'סוויטה ייחודית בעיר העתיקה של צפת, משלבת היסטוריה ופינוק מודרני. מקום מושלם להתנתקות והשראה.',
    isPremium: true,
  }
];

export const getMockAds = () => [
  {
    id: 'ad1',
    type: 'ad', // To distinguish from apartments
    imageUrl: 'https://picsum.photos/seed/ad1/600/400?grayscale&blur=2',
    advertiser: 'מסעדת הדייג הזקן',
    title: 'ארוחה זוגית מפנקת ב-20% הנחה!',
    linkUrl: '#',
    callToAction: 'לפרטים והזמנה',
  },
  {
    id: 'ad2',
    type: 'ad',
    imageUrl: 'https://picsum.photos/seed/ad2/600/400?grayscale',
    advertiser: 'טיולי ג\'יפים בצפון',
    title: 'חווית שטח בלתי נשכחת לכל המשפחה!',
    linkUrl: '#',
    callToAction: 'גלו מסלולים',
  }
];
